# Generated by Django 5.2 on 2025-04-05 01:02

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to=api.models.conversation_audio_path),
        ),
        migrations.AddField(
            model_name='conversation',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duration of the audio in seconds', null=True),
        ),
    ]
