# Generated by Django 5.2 on 2025-04-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_conversation_analysis_results_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='status_transcription',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
