# Generated by Django 5.2 on 2025-04-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_conversation_recap_text_conversation_status_recap'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='status_summary',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='conversation',
            name='summary_data',
            field=models.JSONField(blank=True, default=dict, help_text='JSON object containing short, balanced, and detailed summaries', null=True),
        ),
    ]
