# Generated by Django 5.2 on 2025-04-13 19:35

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_conversation_user'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='userprofile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('resume', models.FileField(blank=True, help_text="User's uploaded resume file (PDF, DOCX, etc.).", null=True, upload_to=api.models.resume_upload_path)),
                ('job_description', models.FileField(blank=True, help_text='Uploaded job description file (PDF, DOCX, etc.).', null=True, upload_to=api.models.job_description_upload_path)),
            ],
        ),
    ]
