# Generated by Django 5.2 on 2025-05-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='generated_mock_questions',
            field=models.JSONField(blank=True, help_text='Generated mock interview questions based on resume and JD (stored as a list of strings).', null=True),
        ),
    ]
