# Generated by Django 5.2 on 2025-05-19 00:41

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_userprofile_generated_mock_questions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Untitled Interview', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('questions_used', models.JSONField(blank=True, help_text='List of questions asked during this interview.', null=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to=api.models.interview_audio_path)),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Duration of the audio in seconds', null=True)),
                ('status_transcription', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('transcription_text', models.JSONField(blank=True, help_text='Raw transcription result (JSON)', null=True)),
                ('status_analysis', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('analysis_results', models.JSONField(blank=True, default=dict, help_text='JSON object for interview analysis', null=True)),
                ('status_coaching', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('coaching_feedback', models.TextField(blank=True, help_text='Generated coaching feedback for the interview', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
