# Generated by Django 5.2 on 2025-05-24 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_interview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='duration',
        ),
        migrations.AddField(
            model_name='interview',
            name='answer_audio_s3_keys',
            field=models.JSONField(blank=True, default=list, help_text='List of S3 keys for individual answer audio files.', null=True),
        ),
    ]
