# Generated by Django 5.2 on 2025-05-24 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_interview_audio_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='answer_transcripts_json',
            field=models.JSONField(blank=True, default=list, help_text='List of structured JSON transcription results for each answer.', null=True),
        ),
    ]
