    # netlify.toml at repository root
    [build]
      base    = "landing-page"  # Directory to change to before starting build
      publish = ".next" # Path to deploy folder (relative to repo root)
      command = "npm run build"     # Build command